# Generated by Django 5.0.3 on 2024-03-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_dish_options_alter_dish_cooks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtype',
            name='name',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
