# Generated by Django 5.0.3 on 2024-03-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_alter_dishtype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'ordering': ('username',)},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('name',), 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ('name',)},
        ),
    ]
